[workspace]
members = [
    "memory",
    "vm",
    "compiler",
    "constraints",
    "achronyme-parser",
    "cli",
    "ir",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
