[package]
name = "cli"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
byteorder = "1.5"

memory = { path = "../memory" }
vm = { path = "../vm" }
compiler = { path = "../compiler" }
constraints = { path = "../constraints" }
ir = { path = "../ir" }
